---
title: "HR projekt Analiza danych"
date: "`r Sys.Date()`"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "default"
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```

# Wczytanie danych z pliku CSV
dane <- read.csv(file="HR.csv") 

# Kolejne wczytanie danych z nagłówkami i specyficznymi separatorami
tabela <- read.csv("HR.csv", header= TRUE, sep=",", dec=",")

# Wyświetlenie danych
View(tabela)

# Sprawdzenie liczby brakujących wartości w całym zbiorze danych
sum(is.na(tabela)) 

library(DataExplorer)

# Wizualizacja brakujących danych
plot_missing(tabela)

# Sprawdzenie kompletności wierszy
complete.cases(tabela)

# rows_with_na przechowuje indeksy wierszy, które zawierają brakujące wartości.
rows_with_na <- which(!complete.cases(tabela))

# Wyświetlenie wierszy z brakującymi wartościami
tabela[rows_with_na, ]

# Znalezienie kolumn z brakującymi wartościami
cols_with_na <- which(colSums(is.na(tabela)) > 0)

# Wyświetla nazwy kolumn, które zawierają brakujące dane
names(tabela)[cols_with_na]

library(naniar)
library(ggplot2)

gg_miss_var(tabela) +
  labs(
    title = "Shadowmapa brakujących danych",
    x = "Kolumny",
    y = "Liczba brakujących wartości"
  )
 
# braki danych
vis_miss(tabela)
 
# podumowanie braków danych
miss_var_summary(tabela)
 
# wizualizacja braków danych
gg_miss_upset(tabela)
 
# Wykryj wzorce braków danych
gg_miss_var(tabela)

# z wykresu wynika, że nie ma wzorca braku danych, są one niezależne
# jest tylko kilka przypadków, gdzie brakuje więcej niż jednej zmiennej w wierszu, ale nie można tego uznać za regułę

# wypełnienie braków danych


